### ISSUE TITLE
NullReferenceException issue

### ISSUE THREAD

**Issue by ghost1372** [rasyidf/UFA.Localization#9] opened 2020-03-25 12:29 UTC
hi why i get NullReferenceException ?

this is how i get string 
` string test = LocalizationService.GetString("3", "Text", "آیا مایل به تغییر زبان برنامه هستید؟");`

and this is my json
```
{
  "Languages": [
    {
      "EnglishName": "English",
      "CultureName": "United States",
      "Culture": "en-US",
      "RTL": "false"
    },
    {
      "EnglishName": "Persian",
      "CultureName": "Farsi",
      "Culture": "fa-IR",
      "RTL": "true"
    }
  ],

  "Data": [
    {
      "data": [
        {
          "Id": 2,
          "Header": {
            "en-US": "Exit",
            "fa-IR": "بستن"
          }
        },
        {
          "Id": 3,
          "Text": {
            "en-US": "do you want to change language?",
            "fa-IR": "آیا مایل به تغییر زبان برنامه هستید؟"
          }
        },
        {
          "Id": 10,
          "Content": {
            "en-US": "Subtitle",
            "fa-IR": "زیرنویس"
          }
        }
      ]
    }
  ]
}
```

**Comment by rasyidf** [comment] 2020-04-03 08:21
I'm still searching the causes. thank you for your feedback

**Comment by SKProCH** [comment] 2020-04-03 09:08
This usually occurs because localization is requested before it loads.
I fix this and implement some cool features [here](https://gitlab.com/SKProCH/localization), feel free to look and pull request (?) (i don't know how to interacts between gitlab and github)

**Comment by rasyidf** [comment] 2020-04-03 09:17
well, thank you. I'll try to implement it into github also.

I don't know either how to interact between both.

**Comment by SKProCH** [comment] 2020-04-03 09:21
Wait a few hours, I'll move it out on github

**Comment by rasyidf** [comment] 2020-04-03 09:24
yes, thank you :)

**Comment by rasyidf** [comment] 2020-04-03 09:43
Then i'll close this issue.

**Closed as completed by rasyidf** 2020-04-03 09:43 UTC
Labels: bug
